import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const { Pool } = pg;

const pgSchema = `
  CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );

  CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);
  CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);

  CREATE TABLE IF NOT EXISTS leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode TEXT NOT NULL CHECK(mode IN ('pve')),
    score INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    kills INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, mode)
  );
`;

function normalizeSql(sql) {
  return String(sql).replace(/\s+/g, ' ').trim().toLowerCase();
}

function defaultLocalDbFile() {
  const dirname = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(dirname, '../../.data/local-db.json');
}

class LocalJsonDatabase {
  constructor(filePath) {
    this.filePath = filePath;
    this.state = {
      nextUserId: 1,
      nextSessionId: 1,
      nextLeaderboardId: 1,
      users: [],
      sessions: [],
      leaderboard: []
    };
    this.load();
  }

  load() {
    fs.mkdirSync(path.dirname(this.filePath), { recursive: true });
    if (!fs.existsSync(this.filePath)) {
      this.save();
      return;
    }

    try {
      const parsed = JSON.parse(fs.readFileSync(this.filePath, 'utf8'));
      this.state = { ...this.state, ...parsed };
    } catch {
      const backupPath = `${this.filePath}.broken-${Date.now()}`;
      fs.renameSync(this.filePath, backupPath);
      this.save();
      console.warn(`[db] Local DB was corrupted. Backup saved to ${backupPath}`);
    }
  }

  save() {
    fs.writeFileSync(this.filePath, JSON.stringify(this.state, null, 2));
  }

  deleteExpiredSessions() {
    const now = Date.now();
    const before = this.state.sessions.length;
    this.state.sessions = this.state.sessions.filter((session) => Date.parse(session.expires_at) > now);
    if (this.state.sessions.length !== before) this.save();
  }

  async query(sql, params = []) {
    const normalized = normalizeSql(sql);

    if (normalized.startsWith('delete from sessions where expires_at <= now()')) {
      this.deleteExpiredSessions();
      return { rows: [], rowCount: 0 };
    }

    if (normalized.startsWith('insert into users')) {
      const [username, passwordHash] = params;
      if (this.state.users.some((user) => user.username.toLowerCase() === String(username).toLowerCase())) {
        const error = new Error('duplicate username');
        error.code = '23505';
        throw error;
      }

      const now = new Date().toISOString();
      const user = {
        id: String(this.state.nextUserId++),
        username: String(username),
        password_hash: String(passwordHash),
        created_at: now
      };
      this.state.users.push(user);
      this.save();
      return { rows: [{ id: user.id, username: user.username }], rowCount: 1 };
    }

    if (normalized.startsWith('insert into sessions')) {
      const [userId, tokenHash, expiresAt] = params;
      const now = new Date().toISOString();
      const session = {
        id: String(this.state.nextSessionId++),
        user_id: String(userId),
        token_hash: String(tokenHash),
        created_at: now,
        last_seen_at: now,
        expires_at: new Date(expiresAt).toISOString()
      };
      this.state.sessions.push(session);
      this.save();
      return { rows: [], rowCount: 1 };
    }

    if (normalized.startsWith('update sessions set last_seen_at = now() where id =')) {
      const [sessionId] = params;
      const session = this.state.sessions.find((item) => String(item.id) === String(sessionId));
      if (session) {
        session.last_seen_at = new Date().toISOString();
        this.save();
      }
      return { rows: [], rowCount: session ? 1 : 0 };
    }

    if (normalized.startsWith('delete from sessions where token_hash =')) {
      const [tokenHash] = params;
      const before = this.state.sessions.length;
      this.state.sessions = this.state.sessions.filter((session) => session.token_hash !== tokenHash);
      this.save();
      return { rows: [], rowCount: before - this.state.sessions.length };
    }

    if (normalized.startsWith('insert into leaderboard')) {
      const [userId, mode, score, wins, kills] = params;
      if (mode !== 'pve') return { rows: [], rowCount: 0 };
      let row = this.state.leaderboard.find((item) => String(item.user_id) === String(userId) && item.mode === mode);
      const now = new Date().toISOString();
      if (!row) {
        row = {
          id: String(this.state.nextLeaderboardId++),
          user_id: String(userId),
          mode,
          score: 0,
          wins: 0,
          kills: 0,
          updated_at: now
        };
        this.state.leaderboard.push(row);
      }
      row.score += Number(score ?? 0);
      row.wins += Number(wins ?? 0);
      row.kills += Number(kills ?? 0);
      row.updated_at = now;
      this.save();
      return { rows: [], rowCount: 1 };
    }

    throw new Error(`Local DB query is not implemented: ${normalized}`);
  }

  async one(sql, params = []) {
    const normalized = normalizeSql(sql);

    if (normalized.startsWith('select * from users where username =')) {
      const [username] = params;
      return this.state.users.find((user) => user.username === username) ?? null;
    }

    if (normalized.includes('from sessions s join users u')) {
      const [tokenHash] = params;
      this.deleteExpiredSessions();
      const session = this.state.sessions.find((item) => item.token_hash === tokenHash && Date.parse(item.expires_at) > Date.now());
      if (!session) return null;
      const user = this.state.users.find((item) => String(item.id) === String(session.user_id));
      if (!user) return null;
      return {
        session_id: session.id,
        user_id: session.user_id,
        expires_at: session.expires_at,
        id: user.id,
        username: user.username,
        created_at: user.created_at
      };
    }

    if (normalized.startsWith('select id, username, created_at from users where id =')) {
      const [userId] = params;
      const user = this.state.users.find((item) => String(item.id) === String(userId));
      return user ? { id: user.id, username: user.username, created_at: user.created_at } : null;
    }

    const result = await this.query(sql, params);
    return result.rows[0] ?? null;
  }

  async many(sql, params = []) {
    const normalized = normalizeSql(sql);

    if (normalized.includes('from leaderboard l join users u')) {
      return this.state.leaderboard
        .filter((row) => row.mode === 'pve')
        .map((row) => {
          const user = this.state.users.find((item) => String(item.id) === String(row.user_id));
          return {
            username: user?.username ?? 'Unknown',
            mode: row.mode,
            score: row.score,
            wins: row.wins,
            kills: row.kills,
            updated_at: row.updated_at
          };
        })
        .sort((a, b) => (b.score - a.score) || (b.wins - a.wins) || (b.kills - a.kills))
        .slice(0, 10);
    }

    const result = await this.query(sql, params);
    return result.rows;
  }

  async close() {}
}

function shouldUsePostgres() {
  const driver = String(process.env.DB_DRIVER ?? '').toLowerCase();
  if (driver === 'postgres' || driver === 'pg') return true;
  if (driver === 'local' || driver === 'json') return false;
  return /^postgres(ql)?:\/\//i.test(process.env.DATABASE_URL ?? '');
}

async function createPostgresDatabase() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is required when DB_DRIVER=postgres.');
  }

  const pool = new Pool({
    connectionString,
    max: Number(process.env.PG_POOL_SIZE ?? 10),
    ssl: process.env.PG_SSL === 'true' ? { rejectUnauthorized: false } : undefined
  });

  await pool.query(pgSchema);

  return {
    driver: 'postgres',
    pool,
    async query(text, params = []) {
      return pool.query(text, params);
    },
    async one(text, params = []) {
      const result = await pool.query(text, params);
      return result.rows[0] ?? null;
    },
    async many(text, params = []) {
      const result = await pool.query(text, params);
      return result.rows;
    },
    async close() {
      await pool.end();
    }
  };
}

export async function createDatabase() {
  if (shouldUsePostgres()) return createPostgresDatabase();

  const filePath = process.env.LOCAL_DB_FILE
    ? path.resolve(process.env.LOCAL_DB_FILE)
    : defaultLocalDbFile();

  console.warn(`[db] Using local JSON database: ${filePath}`);
  console.warn('[db] For production/Render set DB_DRIVER=postgres and DATABASE_URL.');

  const localDb = new LocalJsonDatabase(filePath);
  return {
    driver: 'local-json',
    async query(text, params = []) {
      return localDb.query(text, params);
    },
    async one(text, params = []) {
      return localDb.one(text, params);
    },
    async many(text, params = []) {
      return localDb.many(text, params);
    },
    async close() {
      return localDb.close();
    }
  };
}
